# Merges all population/*.sql parts into a single population.sql file for MySQL import.
# Run this script from the database folder: powershell -ExecutionPolicy Bypass -File .\merge_population.ps1
# powershell -NoProfile -ExecutionPolicy Bypass -File merge_population.ps1


$parts = @(
  "population/00_reset.sql",
  "population/01_semesters.sql",
  "population/02_users.sql",
  "population/03_programs.sql",
  "population/04_courses.sql",
  "population/05_course_dependencies.sql",
  "population/06_program_requirement_groups.sql",
  "population/07_requirement_group_courses.sql",
  "population/08_recommended_sequences.sql",
  "population/09_student_profiles_and_programs.sql",
  "population/10_student_transcripts.sql",
  "population/11_student_plan_drafts.sql",
  "population/12_student_plans.sql",
  "population/13_semester_approvals.sql",
  "population/14_student_plan_semesters.sql"
)

$dest = "population.sql"

if (-not (Test-Path "population")) {
  throw "population folder not found. Run this script from the database directory."
}

$header = @"
-- Degree planner population (merged)
-- Generated by merge_population.ps1
-- Import with: mysql -u <user> -p goplan < population.sql
"@

Set-Content -Path $dest -Value $header -Encoding UTF8

foreach ($part in $parts) {
  if (-not (Test-Path $part)) {
    throw "Missing part file: $part"
  }
  Add-Content -Path $dest -Value ""
  Add-Content -Path $dest -Value "-- ===== Begin $part ====="
  Get-Content -Path $part | Add-Content -Path $dest
  Add-Content -Path $dest -Value "-- ===== End $part ====="
}

Write-Host "Merged $($parts.Count) files into $dest"
